version: "3.9"
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: aggregator

  minio:
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z
    container_name: aggregator_minio_storage
    ports:
    - "9000:9000"
    - "9001:9001"
    volumes:
    - aggregator_minio_data:/data
    hostname: aggregator_minio_host
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://root:root@localhost:27017/students
    depends_on:
      - mongo
      - minio
    command: [ "/app/aggregator" ]

volumes:
  aggregator_minio_data: {}
