version: "3.9"
services:
#  postgres:
#    image: postgres:14-alpine
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=secret
#      - POSTGRES_DB=pg
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/pg?sslmode=disable
#    depends_on:
#      - postgres
    command: [ "/app/aggregator" ]
