project:
  name: &projectName Student Aggregator
  gracefulTimeoutSeconds: 5
  version: 1.0.0
  swaggerEnabled: false
logging:
  projectName: *projectName
  code: zap
  encoding: json
  level: warning
  dateTimeFormat: 2006-01-02 15:04:05
  dateFormat: 2006-01-02
  enableCaller: true
  devMode: false
http:
  accessTokenTTLMinutes: 30
  refreshTokenTTLHours: 24
