name: build and test

on:
  pull_request:
    branches:
      - master
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # - Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Disabled. We do not need build now.
#      - name: Build
#        run: go build -v ./...

      - name: Test
        run: go test -v ./...
