name: Student Aggregator

on:
  push:
    branches:
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      # Disabled. We do not need build now.
#      - name: Build
#        run: go build -v ./...

      - name: Test
        run: go test -v ./...
